_MIN_COMPENDIUM = {
    "Amatsu": {
        "Amaterasu": 79,
        "Ame no Uzume": 22,
        "Take-Mikazuchi": 55
    },
    "Avatar": {
        "Anubis": 60,
        "Barong": 68,
        "Chimera": 46,
        "Kaiming Shou": 40,
        "Kamapua'a": 23,
        "Makami": 33,
        "Shiisaa": 14,
        "Ukano Mitama": 53
    },
    "Avian": {
        "Feng Huang": 63,
        "Garuda": 72,
        "Hamsa": 10,
        "Phoenix": 24,
        "Suparna": 15,
        "Thunderbird": 42,
        "Vidofnir": 34,
        "Yatagarasu": 62
    },
    "Beast": {
        "Ammut": 64,
        "Cerberus": 69,
        "Dormarth": 58,
        "Gryphon": 40,
        "Hairy Jack": 30,
        "Hsing-Hsing": 48,
        "Inugami": 20,
        "Kabuso": 6,
        "Kaso": 10,
        "Nekomata": 35,
        "Orthrus": 52,
        "Stonka": 26
    },
    "Brute": {
        "Azumi": 19,
        "Berserker": 64,
        "Bilwis": 9,
        "Fuu-Ki": 49,
        "Kin-Ki": 43,
        "Momunofu": 25,
        "Ongyo-Ki": 78,
        "Oni": 13,
        "Sui-Ki": 54,
        "Yaksha": 71,
        "Yamawaro": 32,
        "Yomotsu-Ikusa": 37
    },
    "Deity": {
        "Apsu": 82,
        "Baal": 79,
        "Hachiman": 75,
        "Inti": 34,
        "Krishna": 87,
        "Lord Nandou": 48,
        "Mahamayuri": 67,
        "Maitreya": 83,
        "Odin": 85,
        "Omoteotl": 59,
        "Osiris": 53,
        "Prometheus": 40,
        "Thoth": 30
    },
    "Divine": {
        "Angel": 10,
		"Angel (White Wings)": 82,
        "Archangel": 18,
        "Cherub": 71,
        "Dominion": 51,
        "Power": 33,
        "Principality": 26,
        "Throne": 62,
        "Virtue": 41
    },
    "Dragon": {
        "Gucumatz": 27,
        "Huang Long": 78,
        "Illuyanka": 47,
        "Long": 61,
        "Makara": 13,
        "Patrimpas": 20,
        "Quetzalcoatl": 67,
        "Zhu Yin": 55
    },
    "Drake": {
        "Bai Suzhen": 21,
        "Basilisk": 28,
        "Fafnir": 75,
        "Kingu": 39,
        "Mushussu": 47,
        "Niddhoggr": 60,
        "Python": 70,
        "Tiamat": 55,
        "Toubyou": 14,
        "Vasuki": 88,
        "Ym": 65,
        "Zhu Tun She": 8
    },
    "Element": {
        "Aeros": 12,
        "Aquans": 16,
        "Erthys": 8,
        "Flaemis": 20,
        "Gnome": 24,
        "Salamander": 36,
        "Sylph": 28,
        "Undine": 32
    },
    "Enigma": {
        "Futotama": 50,
        "Kama": 72,
        "Kanbari": 27,
        "Kangiten": 80,
        "Kinmamon": 60
    },
    "Entity": {
        "Alilat": 84
    },
    "Fairy": {
        "Demonee-Ho": 76,
        "Goblin": 3,
        "High Pixie": 29,
        "Jack Frost": 20,
        "Kelpie": 31,
        "Lorelei": 58,
        "Nadja": 6,
        "Napaea": 12,
        "Oberon": 64,
        "Pixie": 9,
        "Pyro Jack": 25,
        "Setanta": 35,
        "Silky": 44,
        "Spriggan": 14,
        "Titania": 70,
        "Vivian": 52
    },
    "Fallen": {
        "Adramelech": 68,
        "Barbatos": 69,
        "Bifrons": 20,
        "Botis": 83,
        "Dantalion": 53,
        "Decarabia": 5,
        "Gemori": 58,
        "Halphas": 24,
        "Melchom": 13,
        "Murmur": 63,
        "Nebiros": 46,
        "Orias": 38,
        "Ose": 32,
        "Samael": 90,
        "Shax": 74
    },
    "Famed": {
        "Hagen": 56,
        "Huang Di": 86,
        "Jeanne D'Arc": 42,
        "Kanseiteikun": 67,
        "Lanling Wang": 49,
        "Rama": 74,
        "Siegfried": 62,
        "Tenkai": 77,
        "Tokisada": 80,
        "Yoshitsune": 36
    },
    "Femme": {
        "Atropos": 46,
        "Clotho": 35,
        "Dakini": 63,
        "Kali": 75,
        "Lachesis": 41,
        "Leanan Sidhe": 9,
        "Medusa": 39,
        "Mermaid": 15,
        "Rangda": 68,
        "Shikome": 23,
        "Strix": 17,
        "Taraka": 59,
        "Yuki Jyorou": 30
    },
    "Fiend": {
        "Black Rider": 93,
        "David": 82,
        "Matador": 87,
        "Mother Harlot": 99,
        "Pale Rider": 95,
        "Red Rider": 91,
        "Trumpeter": 97,
        "White Rider": 89
    },
    "Flight": {
        "Caladrius": 4,
        "Da Peng": 56,
        "Gu Huo Niao": 16,
        "Harpy": 35,
        "Rukh": 47,
        "Tangata Manu": 22,
        "Tuofei": 30
    },
    "Food": {
        "Chupacabra": 21,
        "Hare of Inaba": 38,
        "Katakirauwa": 1,
        "Kuda": 27,
        "Mamedanuki": 9,
        "Onmoraki": 5
    },
    "Foul": {
        "Hooligan": 10,
        "Jack the Ripper": 7,
        "Mad Gasser": 37,
        "Night Stalker": 22,
        "Slime": 2,
        "Tattooed Man": 27
    },
    "Fury": {
        "Ares": 32,
        "Asura": 43,
        "Beiji-Weng": 66,
        "Chernobog": 50,
        "Kartikeya": 78,
        "Mitra-Buddha": 96,
        "Shiva": 95,
        "Susano-o": 84,
        "Tonatiuh": 37,
        "Wu Kong": 57
    },
    "Genma": {
        "Baldur": 28,
        "Cu Chulainn": 50,
        "Frost Ace": 42,
        "Hanuman": 66,
        "Heimdall": 73,
        "Ictinike": 18,
        "Jarilo": 61,
        "Kresnik": 56,
        "Kurama Tengu": 43,
        "Nata Taishi": 23,
        "Tam Lin": 13,
        "Tlaloc": 39
    },
    "Ghost": {
        "Churel": 32,
        "Enku": 38,
        "Ghoul": 49,
        "Kudlak": 66,
        "Mou-Ryo": 23,
        "Obariyon": 18,
        "Preta": 11,
        "Strigoii": 6,
        "Vetala": 74
    },
    "Herald": {
        "Aniel": 90,
        "Azrael": 77,
        "Israfel": 68,
        "Kazfiel": 82,
        "Lailah": 54,
        "Mastema": 93,
        "Merkabah": 99,
        "Metatron": 98,
        "Seraph": 94,
        "Sraosha": 86,
        "Victor": 61
    },
    "Holy": {
        "Airavata": 44,
        "Apis": 18,
        "Baihu": 62,
        "Chironnupu": 26,
        "Heqet": 13,
        "Pabilsag": 24,
        "Qing Niugai": 29,
        "Sleipnir": 55,
        "Sphinx": 71
    },
    "Jaki": {
        "Black Frost": 40,
        "Girimehkala": 62,
        "Gremlin": 8,
        "Grendel": 50,
        "Hekatoncheires": 68,
        "Ippon-Datara": 16,
        "Lham Dearg": 22,
        "Ogre": 45,
        "Rakshasa": 38,
        "Wendigo": 30
    },
    "Jirae": {
        "Dwarf": 8,
        "Gogmagog": 61,
        "Hua Po": 12,
        "Knocker": 17,
        "Kwancha": 22,
        "Sudama": 3,
        "Titan": 37,
        "Tlaltecuhtli": 46,
        "Tsuchigumo": 31
    },
    "Kishin": {
        "Bishamonten": 70,
        "Jikokuten": 65,
        "Koumokuten": 60,
        "Marici": 75,
        "Thor": 80,
        "Zhong Kui": 50,
        "Zouchouten": 55
    },
    "Kunitsu": {
        "Arahabaki": 57,
        "Hitokoto-Nushi": 49,
        "Kushinada-Hime": 40,
        "Okuninushi": 30,
        "Oumitsunu": 65,
        "Sukuna-Hikona": 34,
        "Take-Minakata": 21
    },
    "Lady": {
        "Asherah": 51,
        "Black Maria": 66,
        "Diana": 41,
        "Dzelarhons": 19,
        "Hariti": 36,
        "Inanna": 91,
        "Isis": 59,
        "Pele": 7,
        "Sedna": 27,
        "Skadi": 73,
        "Xi Wangmu": 79
    },
    "Megami": {
        "Anat": 63,
        "Brigid": 33,
        "Cleopatra": 99,
        "Fortuna": 11,
        "Hathor": 18,
        "Ishtar": 44,
        "Izanami": 82,
        "Lakshmi": 77,
        "Norn": 69,
        "Pallas Athena": 51,
        "Parvati": 25,
        "Scathach": 39,
        "Tlazolteotl": 57
    },
    "Night": {
        "Fomorian": 6,
        "Incubus": 23,
        "Kaiwan": 39,
        "Kikimora": 28,
        "Lilim": 33,
        "Maya": 77,
        "Mokoi": 18,
        "Queen Mab": 61,
        "Sandman": 10,
        "Succubus": 45,
        "Wild Hunt": 53
    },
    "Nymph": {
        "Apsaras": 15,
        "Kikuri-Hime": 36,
        "Peri": 62,
        "Sarasvati": 48,
        "Senri": 26
    },
    "Original Angel": {
        "Satan": 120
    },
    "Raptor": {
        "Anzu": 49,
        "Camazotz": 25,
        "Fuxi": 6,
        "Gurr": 42,
        "Hresvelgr": 70,
        "Huoniao": 65,
        "Itsumade": 19,
        "Moh Shuvuu": 12,
        "Zhen": 31
    },
    "Reaper": {
        "Cernunnos": 71,
        "Guedhe": 63,
        "Hel": 43,
        "Ixtab": 76,
        "Mot": 89,
        "Nergal": 81,
        "Orcus": 50,
        "Persephone": 57
    },
    "Snake": {
        "Gui Xian": 60,
        "Naga": 19,
        "Nozuchi": 23,
        "Orochi": 51,
        "Ouroboros": 47,
        "Pendragon": 66,
        "Vouivre": 28,
        "Yurlungur": 29
    },
    "Spirit": {
        "Dybbuk": 10,
        "Garrote": 7,
        "Inferno": 31,
        "Legion": 4,
        "Macabre": 45,
        "Pisaca": 54,
        "Poltergeist": 19,
        "Quicksilver": 25,
        "Wicker Man": 38
    },
    "Tree": {
        "Daphne": 16,
        "Haoma": 54,
        "Kukunochi": 44,
        "Mayahuel": 34,
        "Narcissus": 29,
        "Yggdrasil": 65
    },
    "Tyrant": {
        "Abaddon": 63,
        "Azazel": 69,
        "Balor": 36,
        "Beelzebub": 79,
        "Belial": 70,
        "Chi You": 87,
        "Horkos": 26,
        "King Frost": 30,
        "Loki": 58,
        "Lucifer": 99,
        "Lucifuge": 73,
        "Mara": 92,
		"Mephisto": 99,
        "Mithras": 21,
        "Morax": 14,
        "Samyaza": 76,
        "Surt": 81,
        "Tzitzimitl": 75
    },
    "Undead": {
        "Alice": 49,
        "Corpses": 35,
        "Patriot": 45,
        "Zombie Cop": 17
    },
    "Vermin": {
        "Arachne": 44,
        "Mothman": 11,
        "Myrmecolion": 29,
        "Okiku-Mushi": 34,
        "Ubu": 21
    },
    "Vile": {
        "Alciel": 67,
        "Baphomet": 25,
        "Demiurge": 95,
        "Mishaguji": 37,
        "Pachacamac": 47,
        "Pales": 73,
        "Seth": 80,
        "Taotie": 58
    },
    "Wilder": {
        "Cabracan": 59,
        "Catoblepas": 52,
        "Chagrin": 11,
        "Fenrir": 69,
        "Jueyuan": 26,
        "Manticore": 45,
        "Nue": 39,
        "Peallaidh": 17,
        "Porewit": 7,
        "Raijuu": 33,
        "Taowu": 64
    },
    "Wood": {
        "Alraune": 48,
        "Erlkonig": 70,
        "Mandrake": 4,
        "Shan Xiao": 11,
        "Skogsra": 31,
        "Zaccoum": 41
    },
    "Yoma": {
        "Agathion": 12,
        "Centaur": 4,
        "Dis": 29,
        "Ganesha": 72,
        "Karasu Tengu": 24,
        "Koppa Tengu": 16,
        "Master Therion": 61,
        "Shiwanna": 38,
        "Valkyrie": 43,
        "Vodyanik": 8,
        "Xiuhtecuhtli": 48
    },
    "Zealot": {
        "Aramisaki": 59,
        "Attis": 74,
        "Dionysus": 41,
        "Ogun": 24,
        "Tezcatlipoca": 82
    }
}