_REVERSE_FUSION_CHART = {
    "Aeros": [
        "Divine x Divine",
        "Yoma x Yoma",
        "Raptor x Raptor",
        "Fairy x Fairy",
        "Spirit x Spirit"
    ],
    "Aquans": [
        "Flight x Flight",
        "Wilder x Wilder",
        "Brute x Brute",
        "Femme x Femme",
        "Ghost x Ghost"
    ],
    "Avatar": [
        "Megami x Deity",
        "Megami x Enigma",
        "Avian x Dragon",
        "Tree x Beast",
        "Divine x Holy",
        "Flight x Holy",
        "Flight x Genma",
        "Nymph x Beast",
        "Deity x Holy",
        "Deity x Beast",
        "Holy x Enigma",
        "Genma x Snake",
        "Beast x Kishin",
        "Beast x Zealot",
        "Wilder x Undead",
        "Wilder x Zealot",
        "Wilder x Famed",
        "Vermin x Foul",
        "Dragon x Famed"
    ],
    "Avian": [
        "Herald x Flight",
        "Herald x Avatar",
        "Herald x Holy",
        "Megami x Holy",
        "Tree x Flight",
        "Divine x Flight",
        "Flight x Nymph",
        "Flight x Raptor",
        "Flight x Kishin",
        "Flight x Amatsu",
        "Raptor x Beast",
        "Raptor x Jaki",
        "Raptor x Foul",
        "Raptor x Undead",
        "Raptor x Famed",
        "Holy x Beast",
        "Fairy x Snake",
        "Wilder x Drake",
        "Drake x Zealot"
    ],
    "Beast": [
        "Flight x Snake",
        "Flight x Dragon",
        "Flight x Brute",
        "Flight x Femme",
        "Yoma x Wilder",
        "Deity x Snake",
        "Avatar x Holy",
        "Avatar x Night",
        "Avatar x Food",
        "Holy x Fairy",
        "Holy x Fallen",
        "Holy x Food",
        "Fairy x Jirae",
        "Snake x Foul",
        "Snake x Enigma",
        "Wilder x Brute",
        "Kishin x Night",
        "Fallen x Spirit",
        "Femme x Food",
        "Night x Kunitsu"
    ],
    "Brute": [
        "Divine x Beast",
        "Yoma x Zealot",
        "Wood x Fairy",
        "Deity x Jirae",
        "Holy x Kishin",
        "Genma x Kishin",
        "Genma x Night",
        "Jirae x Jaki",
        "Jirae x Fury",
        "Jirae x Femme",
        "Jirae x Enigma",
        "Snake x Food",
        "Jaki x Zealot",
        "Lady x Femme",
        "Dragon x Fallen",
        "Kishin x Food",
        "Kishin x Fiend",
        "Fallen x Night",
        "Femme x Entity"
    ],
    "Deity": [
        "Herald x Jirae",
        "Megami x Avatar",
        "Megami x Lady",
        "Megami x Entity",
        "Avatar x Genma",
        "Avatar x Fiend",
        "Avatar x Amatsu",
        "Holy x Lady",
        "Holy x Entity",
        "Genma x Fairy",
        "Genma x Fiend",
        "Genma x Famed",
        "Fairy x Fury",
        "Fairy x Zealot",
        "Reaper x Undead",
        "Reaper x Famed",
        "Tyrant x Famed"
    ],
    "Divine": [
        "Herald x Avian",
        "Herald x Tree",
        "Herald x Fairy",
        "Herald x Undead",
        "Megami x Flight",
        "Avian x Flight",
        "Avian x Undead",
        "Tree x Undead",
        "Flight x Fairy",
        "Flight x Fallen",
        "Yoma x Raptor",
        "Yoma x Fairy",
        "Yoma x Night",
        "Nymph x Holy",
        "Nymph x Jirae",
        "Nymph x Kishin",
        "Nymph x Fallen",
        "Deity x Undead",
        "Avatar x Undead",
        "Holy x Undead",
        "Genma x Undead",
        "Fairy x Night",
        "Fairy x Amatsu",
        "Fury x Undead",
        "Dragon x Undead",
        "Kishin x Undead",
        "Fallen x Foul",
        "Fallen x Zealot",
        "Spirit x Zealot"
    ],
    "Dragon": [
        "Tree x Lady",
        "Tree x Entity",
        "Flight x Zealot",
        "Raptor x Wilder",
        "Avatar x Snake",
        "Avatar x Fury",
        "Avatar x Kishin",
        "Avatar x Kunitsu",
        "Holy x Snake",
        "Jirae x Fallen",
        "Snake x Fury",
        "Snake x Kishin",
        "Snake x Fallen",
        "Snake x Brute",
        "Snake x Kunitsu",
        "Snake x Zealot",
        "Kishin x Fallen",
        "Brute x Drake",
        "Drake x Foul",
        "Drake x Undead",
        "Drake x Famed"
    ],
    "Drake": [
        "Divine x Dragon",
        "Flight x Jaki",
        "Flight x Tyrant",
        "Flight x Fiend",
        "Yoma x Wood",
        "Vile x Raptor",
        "Vile x Snake",
        "Raptor x Fallen",
        "Raptor x Fiend",
        "Raptor x Zealot",
        "Wood x Snake",
        "Wood x Tyrant",
        "Snake x Jaki",
        "Snake x Femme",
        "Snake x Tyrant",
        "Snake x Spirit",
        "Snake x Fiend",
        "Wilder x Jaki",
        "Wilder x Tyrant",
        "Wilder x Spirit",
        "Jaki x Fallen",
        "Jaki x Tyrant",
        "Dragon x Foul",
        "Fallen x Tyrant"
    ],
    "Erthys": [
        "Wood x Wood",
        "Beast x Beast",
        "Jirae x Jirae",
        "Vermin x Vermin",
        "Night x Night",
    ],
    "Fairy": [
        "Tree x Genma",
        "Tree x Jirae",
        "Tree x Fiend",
        "Divine x Avatar",
        "Divine x Jaki",
        "Yoma x Nymph",
        "Yoma x Deity",
        "Yoma x Enigma",
        "Nymph x Avatar",
        "Wood x Night",
        "Deity x Food",
        "Holy x Genma",
        "Holy x Fiend",
        "Holy x Kunitsu",
        "Jirae x Brute",
        "Jirae x Night",
        "Jirae x Foul",
        "Fallen x Kunitsu",
        "Brute x Foul"
    ],
    "Fallen": [
        "Megami x Beast",
        "Divine x Jirae",
        "Divine x Fury",
        "Divine x Foul",
        "Divine x Food",
        "Divine x Zealot",
        "Flight x Vermin",
        "Flight x Fury",
        "Flight x Night",
        "Yoma x Kunitsu",
        "Nymph x Raptor",
        "Jirae x Snake",
        "Snake x Vermin",
        "Snake x Dragon",
        "Fury x Dragon",
        "Fury x Kishin",
        "Dragon x Femme",
        "Night x Amatsu"
    ],
    "Femme": [
        "Megami x Food",
        "Nymph x Deity",
        "Nymph x Fury",
        "Nymph x Brute",
        "Nymph x Night",
        "Nymph x Foul",
        "Nymph x Food",
        "Nymph x Kunitsu",
        "Nymph x Enigma",
        "Wood x Zealot",
        "Fairy x Brute",
        "Snake x Lady",
        "Snake x Entity",
        "Lady x Kishin",
        "Lady x Fallen",
        "Lady x Night",
        "Dragon x Kishin",
        "Dragon x Entity",
        "Kishin x Entity",
        "Fallen x Entity",
        "Night x Entity"
    ],
    "Flaemis": [
        "Nymph x Nymph",
        "Snake x Snake",
        "Jaki x Jaki",
        "Fallen x Fallen",
        "Drake x Drake"
    ],
    "Flight": [
        "Herald x Snake",
        "Herald x Brute",
        "Herald x Food",
        "Avian x Tree",
        "Avian x Divine",
        "Avian x Holy",
        "Avian x Beast",
        "Avian x Food",
        "Tree x Snake",
        "Divine x Yoma",
        "Yoma x Snake",
        "Yoma x Drake",
        "Fairy x Beast",
        "Fairy x Spirit",
        "Beast x Foul",
        "Vermin x Zealot",
        "Night x Zealot"
    ],
    "Foul": [
        "Megami x Fallen",
        "Avian x Yoma",
        "Divine x Lady",
        "Divine x Entity",
        "Flight x Wilder",
        "Flight x Drake",
        "Nymph x Vile",
        "Raptor x Jirae",
        "Wood x Fallen",
        "Wood x Brute",
        "Beast x Drake",
        "Jirae x Vermin",
        "Wilder x Fiend",
        "Jaki x Brute",
        "Dragon x Night",
        "Fallen x Food",
        "Brute x Ghost",
        "Femme x Drake",
        "Night x Spirit"
    ],
    "Fury": [
        "Herald x Dragon",
        "Avian x Lady",
        "Avian x Entity",
        "Vile x Zealot",
        "Deity x Kishin",
        "Deity x Fallen",
        "Deity x Kunitsu",
        "Avatar x Dragon",
        "Lady x Dragon",
        "Kishin x Brute",
        "Kishin x Enigma",
        "Kishin x Famed",
        "Tyrant x Undead"
    ],
    "Genma": [
        "Herald x Megami",
        "Megami x Fairy",
        "Megami x Kishin",
        "Avian x Brute",
        "Tree x Yoma",
        "Tree x Fairy",
        "Yoma x Dragon",
        "Wood x Spirit",
        "Deity x Avatar",
        "Deity x Fairy",
        "Deity x Fiend",
        "Avatar x Enigma",
        "Fairy x Lady",
        "Fairy x Enigma",
        "Fairy x Entity",
        "Jaki x Undead",
        "Jaki x Famed",
        "Foul x Ghost"
    ],
    "Ghost": [
        "Divine x Vermin",
        "Yoma x Reaper",
        "Yoma x Jaki",
        "Yoma x Lady",
        "Yoma x Femme",
        "Yoma x Spirit",
        "Yoma x Fiend",
        "Yoma x Entity",
        "Vile x Jaki",
        "Vile x Spirit",
        "Raptor x Brute",
        "Genma x Foul",
        "Fairy x Tyrant",
        "Reaper x Jaki",
        "Reaper x Night",
        "Jaki x Femme",
        "Jaki x Spirit",
        "Jaki x Food",
        "Jaki x Fiend",
        "Brute x Fiend",
        "Night x Fiend"
    ],
    "Gnome": [
        "Tree x Tree",
        "Reaper x Reaper",
        "Lady x Lady",
        "Kishin x Kishin"
    ],
    "Herald": [
        "Megami x Tree",
        "Megami x Dragon",
        "Avian x Avatar",
        "Avian x Fury",
        "Avian x Famed",
        "Tree x Divine",
        "Divine x Deity",
        "Divine x Enigma",
        "Divine x Famed",
        "Flight x Deity",
        "Flight x Enigma",
        "Deity x Amatsu",
        "Fury x Famed"
    ],
    "Holy": [
        "Herald x Beast",
        "Avian x Deity",
        "Avian x Genma",
        "Avian x Fiend",
        "Avian x Enigma",
        "Yoma x Beast",
        "Raptor x Drake",
        "Deity x Lady",
        "Deity x Entity",
        "Avatar x Femme",
        "Genma x Beast",
        "Genma x Fallen",
        "Fairy x Wilder",
        "Beast x Jaki",
        "Beast x Enigma",
        "Beast x Famed",
        "Wilder x Foul",
        "Vermin x Undead",
        "Vermin x Famed",
        "Lady x Enigma",
        "Spirit x Famed",
        "Foul x Food"
    ],
    "Jaki": [
        "Divine x Ghost",
        "Yoma x Vile",
        "Yoma x Brute",
        "Yoma x Tyrant",
        "Nymph x Tyrant",
        "Vile x Wood",
        "Vile x Fairy",
        "Vile x Jirae",
        "Vile x Brute",
        "Vile x Femme",
        "Vile x Night",
        "Holy x Brute",
        "Jirae x Tyrant",
        "Jirae x Ghost",
        "Kishin x Foul",
        "Brute x Femme",
        "Brute x Tyrant",
        "Brute x Spirit",
        "Brute x Food",
        "Femme x Tyrant",
        "Night x Tyrant",
        "Night x Ghost",
        "Tyrant x Spirit",
        "Tyrant x Ghost",
        "Drake x Fiend",
        "Jaki x Jaki"
    ],
    "Jirae": [
        "Tree x Holy",
        "Tree x Amatsu",
        "Tree x Kunitsu",
        "Divine x Wood",
        "Divine x Brute",
        "Yoma x Avatar",
        "Deity x Brute",
        "Avatar x Beast",
        "Holy x Femme",
        "Holy x Night",
        "Fairy x Foul",
        "Jaki x Night",
        "Vermin x Fallen",
        "Fury x Night",
        "Lady x Food",
        "Lady x Kunitsu",
        "Kishin x Femme",
        "Brute x Enigma",
        "Night x Food",
        "Jirae x Jirae"
    ],
    "Kishin": [
        "Avatar x Fairy",
        "Genma x Fury",
        "Genma x Brute",
        "Genma x Femme",
        "Genma x Entity",
        "Jirae x Lady",
        "Jirae x Entity",
        "Jaki x Foul",
        "Fury x Lady",
        "Fury x Brute",
        "Fury x Fiend",
        "Fury x Entity",
        "Lady x Brute",
        "Brute x Kunitsu",
        "Brute x Entity"
    ],
    "Kunitsu": [
        "Tree x Fury",
        "Tree x Kishin",
        "Tree x Brute",
        "Vile x Famed",
        "Wood x Jaki",
        "Deity x Fury",
        "Deity x Dragon",
        "Avatar x Brute",
        "Genma x Lady",
        "Jirae x Zealot",
        "Fury x Enigma",
        "Lady x Fiend",
        "Dragon x Brute",
        "Fallen x Enigma",
        "Brute x Amatsu"
    ],
    "Lady": [
        "Megami x Fury",
        "Megami x Foul",
        "Megami x Famed",
        "Tree x Femme",
        "Yoma x Jirae",
        "Nymph x Dragon",
        "Nymph x Zealot",
        "Wood x Vermin",
        "Fairy x Jaki",
        "Fairy x Femme",
        "Beast x Night",
        "Jirae x Dragon",
        "Fury x Femme",
        "Dragon x Enigma",
        "Fallen x Femme",
        "Femme x Night",
        "Femme x Spirit",
        "Femme x Kunitsu",
        "Spirit x Undead"
    ],
    "Megami": [
        "Herald x Nymph",
        "Herald x Deity",
        "Herald x Genma",
        "Herald x Lady",
        "Herald x Fiend",
        "Herald x Enigma",
        "Herald x Famed",
        "Herald x Entity",
        "Avian x Fairy",
        "Avian x Femme",
        "Tree x Nymph",
        "Divine x Nymph",
        "Divine x Night",
        "Nymph x Genma",
        "Nymph x Fairy",
        "Nymph x Amatsu",
        "Vile x Undead",
        "Jaki x Ghost",
        "Lady x Foul",
        "Femme x Zealot",
        "Foul x Entity"
    ],
    "Night": [
        "Avian x Kishin",
        "Flight x Lady",
        "Flight x Ghost",
        "Flight x Entity",
        "Yoma x Genma",
        "Yoma x Fury",
        "Yoma x Foul",
        "Yoma x Food",
        "Nymph x Spirit",
        "Raptor x Fairy",
        "Genma x Dragon",
        "Genma x Food",
        "Fairy x Dragon",
        "Fairy x Fallen",
        "Fairy x Kunitsu",
        "Beast x Femme",
        "Dragon x Fiend",
        "Fallen x Brute"
    ],
    "Nymph": [
        "Herald x Femme",
        "Megami x Avian",
        "Megami x Yoma",
        "Megami x Brute",
        "Megami x Night",
        "Megami x Undead",
        "Tree x Avatar",
        "Divine x Genma",
        "Divine x Fairy",
        "Divine x Femme",
        "Flight x Yoma",
        "Raptor x Femme",
        "Snake x Amatsu",
        "Lady x Undead",
        "Femme x Foul",
        "Femme x Amatsu",
        "Night x Drake"
    ],
    "Raptor": [
        "Avian x Fallen",
        "Avian x Night",
        "Avian x Foul",
        "Divine x Vile",
        "Divine x Wilder",
        "Divine x Tyrant",
        "Divine x Drake",
        "Flight x Vile",
        "Flight x Wood",
        "Flight x Jirae",
        "Flight x Spirit",
        "Flight x Food",
        "Vile x Wilder",
        "Vile x Vermin",
        "Vile x Fallen",
        "Vile x Ghost",
        "Wood x Drake",
        "Wilder x Fallen",
        "Vermin x Night",
        "Vermin x Tyrant",
        "Fallen x Drake"
    ],
    "Reaper": [
        "Herald x Fury",
        "Nymph x Fiend",
        "Vile x Tyrant",
        "Wood x Ghost",
        "Wood x Fiend",
        "Deity x Genma",
        "Deity x Foul",
        "Genma x Jirae",
        "Genma x Enigma",
        "Fairy x Fiend",
        "Tyrant x Foul",
        "Spirit x Fiend",
        "Foul x Enigma"
    ],
    "Salamander": [
        "Herald x Herald",
        "Deity x Deity",
        "Tyrant x Tyrant",
        "Kunitsu x Kunitsu"
    ],
    "Snake": [
        "Tree x Dragon",
        "Divine x Kishin",
        "Flight x Foul",
        "Flight x Kunitsu",
        "Yoma x Holy",
        "Yoma x Fallen",
        "Deity x Femme",
        "Avatar x Fallen",
        "Holy x Fury",
        "Holy x Amatsu",
        "Beast x Wilder",
        "Beast x Fury",
        "Beast x Lady",
        "Beast x Fallen",
        "Beast x Brute",
        "Beast x Entity",
        "Jirae x Drake",
        "Dragon x Food",
        "Femme x Enigma",
        "Snake x Snake"
    ],
    "Spirit": [
        "Flight x Reaper",
        "Nymph x Reaper",
        "Nymph x Ghost",
        "Raptor x Reaper",
        "Raptor x Vermin",
        "Wood x Reaper",
        "Holy x Jirae",
        "Fairy x Reaper",
        "Beast x Reaper",
        "Jirae x Reaper",
        "Jirae x Fiend",
        "Snake x Reaper",
        "Reaper x Wilder",
        "Reaper x Vermin",
        "Reaper x Brute",
        "Reaper x Femme",
        "Reaper x Drake",
        "Reaper x Ghost",
        "Reaper x Food",
        "Wilder x Vermin",
        "Vermin x Drake",
        "Vermin x Fiend",
        "Brute x Night",
        "Femme x Ghost",
        "Femme x Fiend"
    ],
    "Sylph": [
        "Avian x Avian",
        "Holy x Holy",
        "Fury x Fury",
        "Dragon x Dragon"
    ],
    "Tree": [
        "Herald x Yoma",
        "Megami x Nymph",
        "Megami x Genma",
        "Megami x Jirae",
        "Megami x Fiend",
        "Avian x Nymph",
        "Nymph x Wood",
        "Wood x Foul",
        "Wood x Undead",
        "Wood x Famed",
        "Avatar x Jirae",
        "Avatar x Lady",
        "Avatar x Entity",
        "Holy x Dragon",
        "Fairy x Kishin",
        "Jirae x Kishin",
        "Jirae x Famed",
        "Vermin x Spirit",
        "Spirit x Foul"
    ],
    "Tyrant": [
        "Yoma x Kishin",
        "Vile x Reaper",
        "Vile x Foul",
        "Vile x Fiend",
        "Reaper x Fallen",
        "Reaper x Zealot",
        "Jaki x Drake",
        "Fury x Fallen",
        "Fury x Foul",
        "Fallen x Fiend",
        "Foul x Zealot"
    ],
    "Undine": [
        "Megami x Megami",
        "Vile x Vile",
		"Avatar x Avatar",
        "Genma x Genma"
    ],
    "Vermin": [
        "Divine x Snake",
        "Flight x Avatar",
        "Raptor x Snake",
        "Raptor x Tyrant",
        "Raptor x Food",
        "Wood x Jirae",
        "Wood x Wilder",
        "Wood x Femme",
        "Holy x Foul",
        "Jirae x Spirit",
        "Jirae x Food",
        "Snake x Wilder",
        "Snake x Drake",
        "Wilder x Night",
        "Wilder x Food",
        "Drake x Food"
    ],
    "Vile": [
        "Herald x Divine",
        "Herald x Foul",
        "Tree x Fallen",
        "Divine x Reaper",
        "Divine x Fiend",
        "Raptor x Wood",
        "Reaper x Tyrant",
        "Reaper x Foul",
        "Reaper x Fiend",
        "Fallen x Amatsu",
        "Tyrant x Fiend",
        "Tyrant x Zealot",
        "Foul x Fiend"
    ],
    "Wilder": [
        "Yoma x Vermin",
        "Vile x Beast",
        "Vile x Drake",
        "Vile x Food",
        "Raptor x Spirit",
        "Raptor x Ghost",
        "Wood x Beast",
        "Wood x Food",
        "Avatar x Foul",
        "Beast x Snake",
        "Beast x Vermin",
        "Beast x Dragon",
        "Beast x Tyrant",
        "Beast x Spirit",
        "Beast x Ghost",
        "Beast x Food",
        "Beast x Fiend",
        "Jaki x Vermin",
        "Vermin x Brute",
        "Tyrant x Drake",
        "Tyrant x Food",
        "Spirit x Food"
    ],
    "Wood": [
        "Megami x Snake",
        "Tree x Foul",
        "Tree x Food",
        "Nymph x Snake",
        "Raptor x Night",
        "Fairy x Vermin",
        "Fairy x Drake",
        "Fairy x Ghost",
        "Jirae x Wilder",
        "Snake x Ghost",
        "Reaper x Spirit",
        "Wilder x Ghost",
        "Vermin x Ghost",
        "Vermin x Food",
        "Drake x Spirit",
        "Drake x Ghost",
        "Spirit x Ghost"
    ],
    "Yoma": [
        "Herald x Night",
        "Megami x Divine",
        "Avian x Jirae",
        "Tree x Deity",
        "Tree x Night",
        "Tree x Enigma",
        "Divine x Spirit",
        "Flight x Beast",
        "Nymph x Jaki",
        "Deity x Night",
        "Fairy x Food",
        "Beast x Jirae",
        "Snake x Night",
        "Fury x Food",
        "Fallen x Ghost",
        "Brute x Zealot",
        "Night x Foul",
        "Night x Enigma"
    ]
}