_MIN_COMPENDIUM = {
    "Chariot": {
        "Agathion": 3,
        "Ara Mitama": 31,
        "Cerberus": 55,
        "Chi You": 86,
        "Kin-Ki": 25,
        "Shiisaa": 16,
        "Shiki-Ouji": 21,
        "Slime": 10,
        "Thor": 64,
        "White Rider": 39
    },
    "Death": {
        "Alice": 79,
        "Chernobog": 62,
        "Hell Biker": 39,
        "Mandrake": 3,
        "Matador": 19,
        "Mokoi": 9,
        "Mot": 72,
        "Pale Rider": 53,
        "Pisaca": 29,
        "Thanatos": 65,
        "Thanatos Picaro": 69
    },
    "Devil": {
        "Andras": 10,
        "Baphomet": 58,
        "Beelzebub": 84,
        "Belial": 68,
        "Flauros": 25,
        "Incubus": 5,
        "Lilim": 32,
        "Nebiros": 62,
        "Pazuzu": 43
    },
    "Emperor": {
        "Baal": 75,
        "Barong": 52,
        "Eligor": 16,
        "King Frost": 61,
        "Oberon": 66,
        "Odin": 82,
        "Okuninushi": 44,
        "Setanta": 28,
        "Thoth": 36
    },
    "Empress": {
        "Dakini": 50,
        "Hariti": 40,
        "Kali": 77,
        "Lamia": 26,
        "Mother Harlot": 80,
        "Titania": 56,
        "Yaksini": 20
    },
    "Fool": {
        "Arsene": 1,
        "Black Frost": 67,
        "Bugs": 49,
        "Decarabia": 32,
        "Dionysus": 61,
        "High Pixie": 16,
        "Izanagi": 20,
        "Izanagi Picaro": 23,
        "Legion": 38,
        "Obariyon": 8,
        "Orpheus": 26,
        "Orpheus Picaro": 29,
        "Ose": 42,
        "Satanael": 95,
        "Vishnu": 83
    },
    "Fortune": {
        "Ariadne": 30,
        "Ariadne Picaro": 42,
        "Asterius": 56,
        "Asterius Picaro": 62,
        "Atropos": 39,
        "Clotho": 26,
        "Fortuna": 46,
        "Lachesis": 34,
        "Lakshmi": 69,
        "Norn": 52
    },
    "Hanged Man": {
        "Attis": 82,
        "Hecatoncheires": 42,
        "Hua Po": 9,
        "Inugami": 14,
        "Moloch": 60,
        "Orthrus": 21,
        "Take-Minakata": 29,
        "Vasuki": 68
    },
    "Hermit": {
        "Arahabaki": 35,
        "Bicorn": 4,
        "Ippon-Datara": 13,
        "Koropokkuru": 9,
        "Koumokuten": 49,
        "Kumbhanda": 42,
        "Kurama Tengu": 56,
        "Naga": 24,
        "Ongyo-Ki": 75,
        "Sudama": 17
    },
    "Hierophant": {
        "Anzu": 25,
        "Berith": 9,
        "Bishamonten": 67,
        "Daisoujou": 42,
        "Phoenix": 22,
        "Forneus": 63,
        "Kohryu": 76,
        "Orobas": 17,
        "Unicorn": 39
    },
    "Judgement": {
        "Abaddon": 74,
        "Anubis": 37,
        "Messiah": 81,
        "Messiah Picaro": 90,
        "Michael": 87,
        "Satan": 92,
        "Shiva": 82,
        "Trumpeter": 59,
        "Yamata-no-Orochi": 64
    },
    "Justice": {
        "Angel": 12,
        "Archangel": 16,
        "Dominion": 68,
        "Melchizedek": 60,
        "Metatron": 89,
        "Power": 41,
        "Principality": 29,
        "Throne": 71,
        "Uriel": 81
    },
    "Lovers": {
        "Ame-no-Uzume": 29,
        "Ishtar": 85,
        "Kushinada-Hime": 42,
        "Leanan Sidhe": 19,
        "Narcissus": 50,
        "Parvati": 56,
        "Pixie": 2,
        "Raphael": 78,
        "Saki Mitama": 6
    },
    "Magician": {
        "Choronzon": 28,
        "Futsunushi": 76,
        "Jack Frost": 11,
        "Jack-o'-Lantern": 2,
        "Nekomata": 17,
        "Queen Mab": 43,
        "Rangda": 48,
        "Sandman": 24,
        "Surt": 59
    },
    "Moon": {
        "Black Ooze": 29,
        "Girimehkala": 44,
        "Kaguya": 16,
        "Kaguya Picaro": 25,
        "Lilith": 60,
        "Mothman": 33,
        "Nue": 20,
        "Onmoraki": 12,
        "Sandalphon": 75,
        "Succubus": 7,
        "Sui-Ki": 24,
        "Tsukiyomi": 50,
        "Tsukiyomi Picaro": 55
    },
    "Priestess": {
        "Apsaras": 11,
        "Cybele": 73,
        "Isis": 26,
        "Kikuri-Hime": 40,
        "Sarasvati": 50,
        "Scathach": 45,
        "Silky": 6,
        "Skadi": 55
    },
    "Star": {
        "Ananta": 43,
        "Cu Chulainn": 67,
        "Fuu-Ki": 23,
        "Garuda": 52,
        "Hanuman": 64,
        "Kaiwan": 36,
        "Kodama": 11,
        "Lucifer": 93,
        "Neko Shogun": 30,
        "Sraosha": 80
    },
    "Strength": {
        "Kelpie": 6,
        "Kusi Mitama": 14,
        "Oni": 19,
        "Rakshasa": 24,
        "Siegfried": 69,
        "Valkyrie": 44,
        "Zaou-Gongen": 80,
        "Zouchouten": 31
    },
    "Sun": {
        "Asura-Ou": 76,
        "Ganesha": 53,
        "Horus": 49,
        "Mithras": 39,
        "Quetzalcoatl": 63,
        "Suzaku": 19,
        "Yatagarasu": 57,
        "Yurlungur": 42
    },
    "Temperance": {
        "Ardha": 84,
        "Byakko": 49,
        "Gabriel": 77,
        "Genbu": 7,
        "Jikokuten": 25,
        "Koppa Tengu": 11,
        "Makami": 15,
        "Mithra": 33,
        "Nigi Mitama": 20,
        "Raja Naga": 55,
        "Seiryu": 62
    },
    "Tower": {
        "Belphegor": 37,
        "Black Rider": 59,
        "Jatayu": 32,
        "Mada": 85,
        "Magatsu-Izanagi": 44,
        "Magatsu-Izanagi Picaro": 48,
        "Mara": 73,
        "Red Rider": 41,
        "Seth": 51,
        "Yoshitsune": 79
    }
}
