_REVERSE_FUSION_CHART = {
    "Chariot": [
        "Fool x Lovers",
        "Magician x Temperance",
        "Priestess x Sun",
        "Empress x Strength",
        "Emperor x Justice",
        "Hierophant x Death",
        "Lovers x Hermit",
        "Lovers x Star",
        "Strength x Temperance",
        "Strength x Tower",
        "Death x Devil",
        "Devil x Moon"
    ],
    "Death": [
        "Fool x Magician",
        "Fool x Strength",
        "Magician x Hierophant",
        "Priestess x Justice",
        "Priestess x Hanged Man",
        "Hierophant x Temperance",
        "Lovers x Strength",
        "Strength x Devil",
        "Hanged Man x Temperance",
        "Tower x Star",
        "Sun x Judgement"
    ],
    "Devil": [
        "Magician x Lovers",
        "Priestess x Strength",
        "Priestess x Temperance",
        "Emperor x Hanged Man",
        "Emperor x Temperance",
        "Chariot x Hermit",
        "Chariot x Death",
        "Justice x Moon",
        "Hermit x Sun",
        "Fortune x Star",
        "Death x Star"
    ],
    "Emperor": [
        "Magician x Justice",
        "Priestess x Empress",
        "Empress x Tower",
        "Empress x Judgement",
        "Justice x Fortune",
        "Justice x Temperance",
        "Hermit x Judgement",
        "Fortune x Hanged Man",
        "Tower x Sun"
    ],
    "Empress": [
        "Fool x Tower",
        "Magician x Hanged Man",
        "Priestess x Emperor",
        "Hierophant x Judgement",
        "Lovers x Tower",
        "Lovers x Sun",
        "Justice x Star",
        "Fortune x Temperance",
        "Moon x Sun"
    ],
    "Fool": [
        "Magician x Strength",
        "Empress x Hierophant",
        "Empress x Death",
        "Emperor x Lovers",
        "Hierophant x Strength",
        "Chariot x Hanged Man",
        "Justice x Death",
        "Justice x Devil",
        "Temperance x Devil",
        "Moon x Judgement"
    ],
    "Fortune": [
        "Priestess x Lovers",
        "Empress x Moon",
        "Emperor x Hierophant",
        "Hierophant x Hermit",
        "Chariot x Tower",
        "Strength x Judgement",
        "Hanged Man x Devil",
        "Temperance x Tower",
        "Temperance x Moon",
        "Star x Judgement"
    ],
    "Hanged Man": [
        "Fool x Empress",
        "Magician x Emperor",
        "Priestess x Tower",
        "Hierophant x Justice",
        "Hierophant x Devil",
        "Lovers x Judgement",
        "Justice x Sun",
        "Fortune x Tower",
        "Death x Temperance"
    ],
    "Hermit": [
        "Fool x Hierophant",
        "Magician x Death",
        "Priestess x Star",
        "Empress x Fortune",
        "Emperor x Death",
        "Chariot x Strength",
        "Hanged Man x Tower",
        "Temperance x Judgement",
        "Devil x Sun",
        "Tower x Moon"
    ],
    "Hierophant": [
        "Fool x Temperance",
        "Magician x Devil",
        "Magician x Sun",
        "Priestess x Chariot",
        "Priestess x Moon",
        "Emperor x Hermit",
        "Chariot x Judgement",
        "Justice x Strength",
        "Hermit x Strength",
        "Fortune x Devil",
        "Strength x Death",
        "Hanged Man x Sun",
        "Death x Moon"
    ],
    "Judgement": [
        "Empress x Lovers",
        "Emperor x Sun",
        "Hierophant x Tower",
        "Lovers x Justice",
        "Hermit x Tower",
        "Star x Sun"
    ],
    "Justice": [
        "Fool x Moon",
        "Fool x Sun",
        "Magician x Empress",
        "Magician x Fortune",
        "Priestess x Judgement",
        "Empress x Emperor",
        "Emperor x Devil",
        "Hierophant x Fortune",
        "Hanged Man x Star"
    ],
    "Lovers": [
        "Fool x Fortune",
        "Magician x Hermit",
        "Magician x Moon",
        "Empress x Justice",
        "Empress x Star",
        "Emperor x Star",
        "Hierophant x Sun",
        "Chariot x Moon",
        "Justice x Hanged Man",
        "Devil x Judgement"
    ],
    "Magician": [
        "Fool x Star",
        "Priestess x Hierophant",
        "Priestess x Fortune",
        "Priestess x Death",
        "Lovers x Moon",
        "Justice x Hermit",
        "Strength x Moon",
        "Death x Judgement",
        "Temperance x Sun",
        "Devil x Tower"
    ],
    "Moon": [
        "Fool x Priestess",
        "Fool x Chariot",
        "Priestess x Devil",
        "Lovers x Devil",
        "Chariot x Justice",
        "Chariot x Star",
        "Strength x Star",
        "Strength x Sun",
        "Hanged Man x Death",
        "Tower x Judgement"
    ],
    "Priestess": [
        "Fool x Hermit",
        "Magician x Chariot",
        "Magician x Star",
        "Empress x Hanged Man",
        "Empress x Temperance",
        "Emperor x Judgement",
        "Hierophant x Moon",
        "Chariot x Fortune",
        "Chariot x Sun",
        "Hermit x Devil",
        "Hermit x Moon",
        "Death x Sun"
    ],
    "Star": [
        "Fool x Justice",
        "Empress x Chariot",
        "Emperor x Tower",
        "Hierophant x Chariot",
        "Hermit x Fortune",
        "Hermit x Hanged Man",
        "Fortune x Death",
        "Fortune x Sun",
        "Hanged Man x Judgement"
    ],
    "Strength": [
        "Fool x Death",
        "Magician x Judgement",
        "Empress x Hermit",
        "Emperor x Chariot",
        "Hierophant x Lovers",
        "Lovers x Fortune",
        "Lovers x Temperance",
        "Chariot x Temperance",
        "Hermit x Death",
        "Hermit x Temperance",
        "Hermit x Star",
        "Hanged Man x Moon",
        "Devil x Star"
    ],
    "Sun": [
        "Fool x Judgement",
        "Empress x Devil",
        "Emperor x Fortune",
        "Hierophant x Hanged Man",
        "Lovers x Hanged Man",
        "Justice x Tower",
        "Fortune x Moon",
        "Death x Tower",
        "Temperance x Star"
    ],
    "Temperance": [
        "Fool x Emperor",
        "Fool x Devil",
        "Magician x Priestess",
        "Magician x Tower",
        "Priestess x Hermit",
        "Lovers x Chariot",
        "Lovers x Death",
        "Chariot x Devil",
        "Fortune x Strength",
        "Strength x Hanged Man",
        "Star x Moon"
    ],
    "Tower": [
        "Fool x Hanged Man",
        "Empress x Sun",
        "Emperor x Strength",
        "Emperor x Moon",
        "Hierophant x Star",
        "Justice x Judgement",
        "Fortune x Judgement"
    ]
}
